server:
  port: 8088

spring:
    datasource:
        mysql1:
              name: mysql1
              url: jdbc:mysql://127.0.0.1:3306/adminlte
              #jdbc-url: jdbc:mysql://127.0.0.1:3306/adminlte
              username: root
              password: daixinbao
              # 使用druid数据源
              type: com.alibaba.druid.pool.DruidDataSource
              driver-class-name: com.mysql.jdbc.Driver
              filters: stat,wall,log4j
              maxActive: 20
              initialSize: 1
              maxWait: 60000
              minIdle: 1
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxOpenPreparedStatements: 20
              # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
              connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        oracle1:
            name: oracle1
            url: jdbc:oracle:thin:@192.168.1.6:1521:orcl
            #jdbc-url: jdbc:oracle:thin:@192.168.1.6:1521:orcl
            username: webdb
            password: dxb
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: oracle.jdbc.driver.OracleDriver
            filters: stat,wall,log4j
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select * from dual
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xinbao.*.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check